groups:
  - name: test-alerts
    rules:
      - alert: TestAlert
        expr: up == 0
        for: 2s
        labels:
          severity: critical
        annotations:
          summary: "Test Alert"
          description: "This is a test alert for targets that are down."