groups:
  - name: sensor-data-related-alerts
    rules:
      - alert: HighTemperature
        expr: sensor_data_temperature > 30 # For now I'll set it to 30 degrees (of course Celsius)
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High temperature detected"
          description: "The temperature is above 30°C for more than 1 minute."