global:
  scrape_interval: 15s  # Default scrape interval

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"  # Alertmanager's address; I might change this later

rule_files:
  - "alert_rules.yml"  # I already created the alert rules file in the current dir

scrape_configs:
  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Monitor Data Collector
  - job_name: "data_collector"
    static_configs:
      - targets: ["data_collector:8000"] # Port 8000 for Prometheus metrics

  # Monitor InfluxDB
  - job_name: "influxdb"
    static_configs:
      - targets: ["influxdb:8086"]
